Starting to get injector for dev environment

diff --git a/backend/Makefile b/backend/Makefile
--- a/backend/Makefile
+++ b/backend/Makefile
@@ -14,7 +14,6 @@ VENV = ../.venv
 VENV_ACTIVATE = source $(VENV)/bin/activate
 APP_PATH = src.main:app
 PORT = 8000
-ENVIRONMENT ?= dev
 
 
 help: ## Show this help message
@@ -29,10 +28,9 @@ install: ## Install backend dependencies
 	$(VENV_ACTIVATE) && alembic init migrations || echo "alembic init already started"
 
 # 1) Boot-up 
-# dev: ## Start backend development server
-# 	$(VENV_ACTIVATE) &&  ENVIRONMENT=dev uvicorn $(APP_PATH) --reload --host 0.0.0.0 --port $(PORT)
+dev: ## Start backend development server
+	$(VENV_ACTIVATE) &&  ENVIRONMENT=dev uvicorn $(APP_PATH) --reload --host 0.0.0.0 --port $(PORT)
 	
-
 
 # 2) CI
 lint: ## Run linting and formatting (local dev)
@@ -92,6 +90,14 @@ db-downgrade-specific-version:
 
 
 push_docker: ## MOVE ME TO BAckend
+	$(MAKE) check_enviroment_variables
 	docker login
-	docker buildx build -t javidsegura/url_shortener_backend --platform linux/amd64,linux/arm64 --push -f ./Dockerfile ./
+	docker buildx build -t javidsegura/url_shortener_backend:$(ENVIRONMENT) --platform linux/amd64,linux/arm64 --push -f ./Dockerfile ./
 
+
+check_enviroment_variables:
+	@if [ -z "$$ENVIRONMENT" ]; then \
+		echo "Error: ENVIRONMENT must be defined"; \
+		exit 1; \
+	fi
+	echo "Environment is: $(ENVIRONMENT)"
diff --git a/infra/Makefile b/infra/Makefile
--- a/infra/Makefile
+++ b/infra/Makefile
@@ -9,63 +9,79 @@ RESET = \033[0m
 
 .DEFAULT_GOAL := help
 
-ENVIRONMENT ?= dev
-BACKEND_ENV_FILE = ../backend/.env.$(ENVIRONMENT)
-FRONTEND_ENV_FILE = ../frontend/app/.env.$(ENVIRONMENT)
+BACKEND_ENV_FILE_BASE_PATH = ../backend/.env.$(ENVIRONMENT).base
+BACKEND_ENV_FILE_SYNCED_PATH = ../backend/.env.$(ENVIRONMENT).synced # CAN THIS BE DELETEED?
+FRONTEND_ENV_FILE = ../frontend/app/.env.$(ENVIRONMENT) 
 ANSIBLE_INVENTORY_FILE = ./ansible/inventory/$(ENVIRONMENT).ini
 TERRAFORM_PATH=terraform/environment/$(ENVIRONMENT)
-SYNC_SCRIPT_PATH = ../scripts/sync_terraform_outputs.py
+SYNC_SCRIPT_PATH = scripts.injector
 
 help: ## Show this help message
 	@echo "$(BLUE)Available commands:$(RESET)"
 	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  $(GREEN)%-15s$(RESET) %s\n", $$1, $$2}' $(MAKEFILE_LIST)
 
 install: ## Initialize Terraform
+	$(MAKE) check_enviroment_variables
 	cd $(TERRAFORM_PATH) && terraform init
 	brew install ansible
 	ansible-galaxy collection install community.docker
 
+check: ## Apply Terraform configuration
+	$(MAKE) check_enviroment_variables
+	cd $(TERRAFORM_PATH) && terraform plan
+
+output:
+	$(MAKE) check_enviroment_variables
+	cd $(TERRAFORM_PATH) && terraform output 
+output-json:
+	$(MAKE) check_enviroment_variables
+	cd $(TERRAFORM_PATH) && terraform output -json
+
 up: ## Apply Terraform configuration
-	@echo "Environment is $(ENVIRONMENT)"
+	$(MAKE) check_enviroment_variables
 	cd $(TERRAFORM_PATH) && terraform apply
 
 down: ## Apply Terraform configuration
-	@echo "Environment is $(ENVIRONMENT)"
+	$(MAKE) check_enviroment_variables
 	cd $(TERRAFORM_PATH) && terraform destroy
 
-output:
-	cd $(TERRAFORM_PATH) && terraform output -json
 
 ansible-ping:
+	$(MAKE) check_enviroment_variables
 	ansible all -m ping -i ./ansible/inventory/$(ENVIRONMENT).ini
 
 ansible-up:
 	ansible-playbook ./ansible/playbook/multi-container.yml -i ./ansible/inventory/$(ENVIRONMENT).ini 
 
-sync_backend_env: 
+terraform-check:
+	cd $(TERRAFORM_PATH) && terraform plan
+
+
+sync_backend_env: ## Inject tf outputs into backend dotenv
 	@echo "Syncing Terraform outputs to backend .env..."
-	cp $(BACKEND_ENV_FILE) $(BACKEND_ENV_FILE).synced
-	python3 $(SYNC_SCRIPT_PATH) \
-	   --terraform-path $(TERRAFORM_PATH) \
+	$(MAKE) check_enviroment_variables
+	python3 -m $(SYNC_SCRIPT_PATH) \
 	   --environment $(ENVIRONMENT) \
-	   --backend-env $(BACKEND_ENV_FILE).synced \
-	   --backend-prefixes api_ backend_
+	   --terraform-dir $(TERRAFORM_PATH) \
+	   --base-dotenv-path $(BACKEND_ENV_FILE_BASE_PATH)
 
 sync_frontend_env:
 	@echo "Syncing Terraform outputs to Ansible inventory..."
+	$(MAKE) check_enviroment_variables
 	python3 $(SYNC_SCRIPT_PATH) \
 		--terraform-path $(TERRAFORM_PATH) \
 		--environment $(ENVIRONMENT) \
 		--frontend-env $(FRONTEND_ENV_FILE).synced \
-		--frontend-prefixes server_ frontend_
+		--frontend-prefixes env_frontend_
 
 sync_ansible_inventory:
 	@echo "Syncing Terraform outputs to Ansible inventory..."
+	$(MAKE) check_enviroment_variables
 	python3 $(SYNC_SCRIPT_PATH) \
 		--terraform-path $(TERRAFORM_PATH) \
 		--environment $(ENVIRONMENT) \
 		--ansible-inventory $(ANSIBLE_INVENTORY_FILE) \
-		--ansible-prefixes ssh_ server_ ansible_
+		--ansible-prefixes ansible_
 
 
 sync_envs:
@@ -76,4 +92,9 @@ sync_all:
 	$(MAKE) sync_envs
 	$(MAKE) sync_ansible_inventory
 
-
+check_enviroment_variables:
+	@if [ -z "$$ENVIRONMENT" ]; then \
+		echo "Error: ENVIRONMENT must be defined"; \
+		exit 1; \
+	fi
+	echo "Environment is: $(ENVIRONMENT)"
